"""
app/modules/compliance/model.py

SQLAlchemy model for storing compliance check results.
Each document gets one compliance_results row per check run.
"""
from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Index, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class ComplianceResult(Base):
    """Stores the output of a compliance check run against a document."""
    __tablename__ = "compliance_results"

    id: Mapped[int] = mapped_column(primary_key=True)
    document_id: Mapped[int] = mapped_column(
        ForeignKey("documents.id"), nullable=False, index=True
    )
    checked_at: Mapped[datetime] = mapped_column(
        DateTime, default=lambda: datetime.now(timezone.utc), nullable=False
    )

    # Overall compliance score 0.0–100.0
    compliance_score: Mapped[float] = mapped_column(Float, nullable=False)

    # JSON-serialised dict of individual clause checks: {"clause_name": true/false, ...}
    clause_results: Mapped[str | None] = mapped_column(Text, nullable=True)

    # JSON-serialised list of prohibited terms found: ["term1", "term2"]
    prohibited_terms_found: Mapped[str | None] = mapped_column(Text, nullable=True)

    # JSON-serialised list of missing mandatory clauses
    missing_mandatory_clauses: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Whether the document passes the minimum compliance threshold (score >= 70)
    passes_minimum: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Human-readable summary generated by the compliance checker
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_compliance_results_document_checked", "document_id", "checked_at"),
    )

    @property
    def status(self) -> str:
        if self.compliance_score >= 90:
            return "compliant"
        if self.compliance_score >= 70:
            return "needs_review"
        return "non_compliant"
