"""feat: add clients module — client table

Revision ID: 07745ea1a6ab
Revises: 9e599c7786d4
Create Date: 2026-05-20 16:18:01.582911

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07745ea1a6ab'
down_revision: Union[str, Sequence[str], None] = '9e599c7786d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('clause_results', sa.Text(), nullable=True),
    sa.Column('prohibited_terms_found', sa.Text(), nullable=True),
    sa.Column('missing_mandatory_clauses', sa.Text(), nullable=True),
    sa.Column('passes_minimum', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_results_document_id'), ['document_id'], unique=False)

    with op.batch_alter_table('circular_analyses', schema=None) as batch_op:
        batch_op.alter_column('compliance_signal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('financial_stress_signal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('claims_signal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('regulatory_signal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('market_conduct_signal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_risk_signals',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circular_analyses', schema=None) as batch_op:
        batch_op.alter_column('total_risk_signals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('market_conduct_signal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('regulatory_signal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('claims_signal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('financial_stress_signal',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('compliance_signal',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('compliance_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_results_document_id'))

    op.drop_table('compliance_results')
    # ### end Alembic commands ###
