"""feat: add csp module — csp_score table

Revision ID: 4cf69424aba9
Revises: 07745ea1a6ab
Create Date: 2026-05-20 16:19:22.960576

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf69424aba9'
down_revision: Union[str, Sequence[str], None] = '07745ea1a6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
