"""feat: add compliance module — compliance_result table

Revision ID: 942e478fe635
Revises: 4cf69424aba9
Create Date: 2026-05-20 16:19:45.468185

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942e478fe635'
down_revision: Union[str, Sequence[str], None] = '4cf69424aba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
